// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dezcgvlghshoawlwvaqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlemNndmxnaHNob2F3bHd2YXF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NDI4MzcsImV4cCI6MjA1NzMxODgzN30.yfvJzTeBBEx7j8Hy6n2H13JAsAvaQdxDDc61U9ymWHg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
